### ISSUE TITLE
API credentials are store as plain text in the DB

### ISSUE THREAD

**Issue by martinclaus** [maxfischer2781/indico_sixpay#12]
The JSON API credentials are stored as plain text in the database. To circumvent that, we can store the credentials in the .netrc file of the user running the indico server. This would require a change of the general settings form to allow for selecting file based credentials.

**Comment by ThiefMaster** [comment]
Indico dev here:

- If your server gets compromised, the API credentials can get stolen in any case.
- Due to the use of SQLAlchemy the risk of any kind of SQL injection is incredibly low.

So I'm -1 on this. At least don't make it required. We use this plugin for some smaller Indico instances and we would not want to have to maintain a file via puppet instead of just storing it using the standard plugin settings.

Also, is there even any significant risk if those credentials were compromised? I hope they don't have more permissions than really needed (ie to verify if a transaction was indeed successful...)
